{{- if .Values.rbac.create }}
{{- range $key, $ns := (split "," .Values.watchNamespaces) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  # hardcoded serviceaccount for aerospike statefulsets
  name: aerospike-operator-controller-manager
  namespace: {{ $ns }}
  labels:
    app: {{ include "aerospike-kubernetes-operator.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
{{- with $.Values.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
